<?php
$translate = $this->plugin('translate');
$this->htmlElement('body')->appendAttribute('class', 'login');
?>
<h1><?php echo $translate('Log in'); ?></h1>
<?php echo $this->form($form); ?>
<p class="forgot-password"><?php echo $this->hyperlink($translate('Forgot password?'), $this->url('forgot-password')); ?></p>

<?php $redirect_url = $this->params()->fromQuery('redirect_url'); ?>
<?= $this->hyperlink($this->translate('Log in using CAS'), $this->casLoginUrl(['redirect_url' => $redirect_url])) ?>
